### ISSUE TITLE
Rewrite v-touch as a component for Vue 2.x

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vue-touch#62]
### Problem

When Vue 2.0 came around, I attempted to update the v-touch directive to Vue 2.0's new API.

But we never published it so far, because I wasn't successful to keep the all features due to the API changes foir custom directives in Vue 2.0

### Solution

I decided to rewrite it all as a component. API will look like this:

```html
<v-touch
  tag="div" <!-- default. Use to change the root element rendered by the component -->
  v-on:pan="method"
  v-bind:pan-options="{ ... }"
  
  <!-- short syntax; -->
  @swipe="method"
  :swipe-options="{ ... }"
>
 <p>Slot Content goes here</p>
</v-touch>
```

### Breaking Change & Migrating

Of course,  this means we will have a complete **breaking change** with the version for Vue 1.0.

But I think the upgrade path is pretty simple:
```html
<!-- 1.0 -->
<section v-touch:swipe="method" v-touch-options:swipe="{ ....}"
  <p>Swipe me!</p>
</section>
<!-- 2.0 -->
<v-touch tag="section" @swipe="method" :swipe-options="{ ....}"
  <p>Swipe me!</p>
</v-touch>
```

I'm already 90% done with the working prototype, And will hopefully find time this weekend to do the cleanup.

**Comment by vitalitygithub** [comment]
Here's a error when I use vue-touch#next with webpack.  

`TypeError: Cannot read property 'priority' of undefined(…) `
`
import Vue from 'vue';	
	import VueTouch from 'vue-touch';	
	Vue.use(VueTouch)
`
Could you tell me how this error happened and how to fix it? Many thanks.

**Comment by LinusBorg** [comment]
Coudl you open a new issue? This one is about something else. Thanks.

**Comment by blomdahldaniel** [comment]
This looks so great! Awesome work!

**Comment by LinusBorg** [comment]
I will finish writing some tests over the holidays, it's looking good :)

**Comment by dsonet** [comment]
What if
```
<!-- 1.0 -->
<section class="header" v-touch:swipe="method" v-touch-options:swipe="{ ....}"
  <p>Swipe me!</p>
</section>
```
The root element has some other attributes?

**Comment by LinusBorg** [comment]
Attributes in components are passed to the component's root node. 

And loosing the `tag` attribute would mean that you end up with a div everytime. Not always desirable.

**Comment by ram-you** [comment]
So what is the link to the new v2 (npm) ?

**Comment by LinusBorg** [comment]
I just published VueTouch `2.0.0-beta.1`: 

https://github.com/vuejs/vue-touch/releases/tag/2.0.0-beta.1

**Comment by zhangxinxinWTB** [comment]
This look so great! thx

**Comment by barraponto** [comment]
So if I want to add hammer.js events to my component I should wrap it in a v-touch component?

**Comment by LinusBorg** [comment]
You *can* use HammerJS without vue-touch, of course. If you *want* to use it wrapped as a component, you can with this library

**Comment by ram-you** [comment]
I still have the error on ssr :
`ReferenceError: window is not defined`
using v2.0.0-beta.3

**Comment by LinusBorg** [comment]
@ram-you can you tell me a bit more? where in the source is this error comping up?

**Comment by ram-you** [comment]
I tried your solution:
```
alias: {
  'hammerjs$': 'vue-touch/dist/hammer-ssr.js'
}
```

But now have new error after compilation: 
```
ERROR in app.e58c50a4d0f7aa688e35.js from UglifyJs
SyntaxError: Unexpected token: name (Hammer)
```

**Comment by LinusBorg** [comment]
Can you please open individual issues for these bugs? I can't track them in a single thread.

Thanks

**Comment by jacquescrocker** [comment]
Sorry to reactivate the thread, but I've been using the new component version and it doesn't seem great. Seems like I'm converting or wrapping everything in v-touch tags. 

Having a alternative v-touch directive approach is really important I think, even if it wasn't fully featured. That way I could switch to the component version whenever I need something deep, but for the common tap event handlers, just use the directive.

Wdyt?

**Comment by LinusBorg** [comment]
Might be worthwhile. Can you open an issue as a feature request? Otherwise it will get burried in this closed one.
